name: Build Windows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: |
            ~/haxe/lib/
            ~/haxe/extra/
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/project.xml') }}

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.2"

      - name: Install Lime/OpenFL
        run: |
          haxelib install lime
          haxelib run lime setup
          haxelib install openfl  # Usa install en lugar de git para mayor velocidad

      - name: Install Haxe dependencies
        run: |
          haxelib install flixel
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install hxcpp
          haxelib install linc_luajit
          haxelib install format
          haxelib install hxp

      - name: Build for Windows
        run: haxelib run lime test windows -v

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: export/windows/bin/*.exe