name: Build Windows

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.3.2"

      - name: Install Lime/OpenFL
        run: |
          haxelib install lime
          haxelib run lime setup
          haxelib git openfl https://github.com/openfl/openfl
          haxelib git lime https://github.com/openfl/lime

      - name: Install Haxe dependencies
        run: |
          haxelib install flixel 6.1.0
          haxelib install flixel-ui 2.6.4
          haxelib install flixel-addons 3.3.2
          haxelib install hxcpp 4.3.2
          haxelib install linc_luajit 0.0.7
          haxelib install format 3.8.0

      - name: Cache Haxelib
        uses: actions/cache@v4
        with:
          path: |
            ~/haxe/lib/
            ~/haxe/extra/
          key: ${{ runner.os }}-haxelib-${{ hashFiles('**/project.xml') }}

      - name: Build for Windows
        run: haxelib run lime test windows -v

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: export/windows/bin/*.exe